<a href="https://colab.research.google.com/github/vv2281/MAT-422/blob/main/VV_HW_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#i created this on jupyter lab but then transferred to here as per the
#'homework' instructions in canvas
#make decimal results; easier to read
np.set_printoptions(precision=4, suppress=True)

In [ ]:
#making two vectors

v1 = np.array([1,2])
v2 = np.array([3,1])
#create a linear combination
linear_combination = 2 * v1 + 3 * v2
print("v1 =", v1)
print("v2 =", v2)
print("\n2v1 + 3v2 =", linear_combination)



v1 = [1 2]
v2 = [3 1]

2v1 + 3v2 = [11  7]


In [ ]:
#create a matrix using v1 and v2 as columns
A = np.column_stack((v1, v2))
print("MATRIX A:")
print(A)

#calculate the rank
rank_A = np.linalg.matrix_rank(A)
print("\nRank of A =", rank_A)

MATRIX A:
[[1 3]
 [2 1]]

Rank of A = 2


In [ ]:
#check whether or not the vectors are linearly independent

if rank_A == A.shape[1]:
    print("the vectors are linearly independent.")
else:
    print("the vectors are linearly dependent.")

the vectors are linearly independent.


In [ ]:
##orthogonality
u = np.array([1,1])
v = np.array([1,-2])

#calculate the dot product
dot_product = np.dot(u, v)
print("u =", u)
print("v =", v)
print("\ndot product =", dot_product)

u = [1 1]
v = [ 1 -2]

dot product = -1


In [ ]:
#calculate the vector norms
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
print("norm of u =", norm_u)
print("norm of v =", norm_v)

norm of u = 1.4142135623730951
norm of v = 2.23606797749979


In [ ]:
#normalize vectors
q1 = u / np.linalg.norm(u)
q2 = v /  np.linalg.norm(v)

print("normalized q1 =", q1)
print("normalized q2 =", q2)

print("\nnorm of q1 =", np.linalg.norm(q1))
print("norm of q2 =", np.linalg.norm(q2))

print("\ndot product of q1 and q1 =", np.dot(q1, q2))

normalized q1 = [0.7071 0.7071]
normalized q2 = [ 0.4472 -0.8944]

norm of q1 = 0.9999999999999999
norm of q2 = 0.9999999999999999

dot product of q1 and q1 = -0.3162277660168379


In [ ]:
#vector to project
x = np.array([3,4])

#project x onto q1
projection = np.dot(x, q1) * q1

print("vector x =", x)
print("unit vector q1 =", q1)
print("\nProjection of x onto q1 =", projection)

vector x = [3 4]
unit vector q1 = [0.7071 0.7071]

Projection of x onto q1 = [3.5 3.5]


In [ ]:
#gram-schmidt process

#create two linearly independent vectors
a1 = np.array([1,1], dtype=float)
a2 = np.array([1,2], dtype=float)
print("a1 =", a1)
print("a2 =", a2)

a1 = [1. 1.]
a2 = [1. 2.]


In [ ]:
#normalize a1

q1 = a1 / np.linalg.norm(a1)

print("q1 =", q1)
print("norm of q1 =", np.linalg.norm(q1))

q1 = [0.7071 0.7071]
norm of q1 = 0.9999999999999999


In [ ]:
#project a2 onto q1

projection_a2_q1 = np.dot(a2,q1) * q1

#remove the projection
b2 = a2 - projection_a2_q1

print("projection of a2 onto q1 =", projection_a2_q1)

print("b2 =", b2)

projection of a2 onto q1 = [1.5 1.5]
b2 = [-0.5  0.5]


In [ ]:
#normalize b2
q2 = b2 / np.linalg.norm(b2)

print("q2 =", q2)
print("norm of q2 =", np.linalg.norm(q2))

q2 = [-0.7071  0.7071]
norm of q2 = 0.9999999999999999


In [ ]:
print("q1 =", q1)
print("q2 =", q2)

print("Dot product q1 and q1 =", np.dot(q1, q2))
print("norm of q1 =", np.linalg.norm(q1))
print("norm of q2 =", np.linalg.norm(q2))

q1 = [0.7071 0.7071]
q2 = [-0.7071  0.7071]
Dot product q1 and q1 = 4.440892098500626e-16
norm of q1 = 0.9999999999999999
norm of q2 = 0.9999999999999999


In [ ]:
#create a symmetric matrix

A = np.array([
    [2,1],
    [1,2]
])
print("Matrix A:")
print(A)

Matrix A:
[[2 1]
 [1 2]]


In [ ]:
#calculate eigenvalues and eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[3. 1.]

Eigenvectors:
[[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]


In [ ]:
#select first eigenvalue and eigenvector
lambda_1 = eigenvalues[0]
x1 = eigenvectors[:, 0]

#calculate both sides of Ax = lambda*x

left_side = A @ x1

right_side = lambda_1 * x1

print("eigenvalue =", lambda_1)
print("eigenvector =", x1)

print("\nA @ x =")
print(left_side)

print("\nlambda * x =")
print(right_side)

eigenvalue = 3.0
eigenvector = [0.7071 0.7071]

A @ x =
[2.1213 2.1213]

lambda * x =
[2.1213 2.1213]


In [ ]:
#select second eigenvalue and eigenvector
lambda_2 = eigenvalues[1]
x2 = eigenvectors[:, 1]

left_side = A @ x2

right_side = lambda_1 * x2

print("eigenvalue =", lambda_2)
print("eigenvector =", x2)

print("\nA @ x =")
print(left_side)

print("\nlambda * x =")
print(right_side)

#because the matrix is symmetric, eigenvectors corresponding to different eigenvalues should be orthogonal.

eigenvalue = 1.0
eigenvector = [-0.7071  0.7071]

A @ x =
[-0.7071  0.7071]

lambda * x =
[-2.1213  2.1213]


In [ ]:
#check the dot product of the eigenvectors

dot_eigenvectors = np.dot(x1, x2)

print("dot product of eigenvectors =", dot_eigenvectors)

#result close to zero confirms that the eigenvectors are orthogonal.

dot product of eigenvectors = 0.0
